### ISSUE TITLE
Postgres panoptes adapter

### ISSUE THREAD

**Issue by camallen** [zooniverse/Cellect#38]
Should we rip the panoptes PG adapter out entirely (perhaps leave as an example) and just use https://github.com/zooniverse/cellect_panoptes/ to distribute the panoptes specific adapter?

**Comment by edpaget** [comment]
I think it's fine to leave it here. I don't really see any reason to remove it.

**Comment by camallen** [comment]
Won't this mean that anyone using Cellect manually via the start script with panoptes get all subjects instead of all active subjects? https://github.com/zooniverse/Cellect/blob/master/config.ru#L12

Should we update the code to only select active subjects then via #37 ?

**Comment by edpaget** [comment]
I don't have any strong feelings about this. I don't think makes sense to try to maintain the Postgres adapter in here to always be compatible with Panoptes if we have cellect_panoptes. 

I also think it could be useful to leave the adapter in as an example and because it make it easier to develop cellect further (adding the automatic partitioning and clustering features for example).

**Comment by camallen** [comment]
Ok - let's leave it in, hopefully no one uses this code for large subject sets / users.

We only maintain the Panoptes adapter in cellect_panoptes.
