### ISSUE TITLE
add db check to stats

### ISSUE THREAD

**Issue by camallen** [zooniverse/Cellect#47]
https://github.com/zooniverse/Cellect/blob/3815e20ba583926c484d55f8a6b83098778b4838/lib/cellect/server/api.rb#L22

can we report the status of the adapter connection in the stats root check for the health check?

**Comment by parrish** [comment]
We could, but isn't ActiveRecord handling reconnection in cellect_panoptes?

**Comment by camallen** [comment]
lots of actors had died and the app didn't seem to reconnect properly, something here the health check can use to cycle the nodes out would be useful.

**Comment by camallen** [comment]
also if the db dies and we just hit `/stats` for cellect health it'll report ok

**Comment by parrish** [comment]
Sounds good

**Comment by parrish** [comment]
I added [an interface for reporting adapter stats](https://github.com/zooniverse/Cellect/commit/84268ab39416a8c61efcb1fd332d0a18460495dc#diff-f7b2789aea832916963b5e6b9081113eR37) along with providing some more useful information in that response.

Since Cellect doesn't only provides abstract adapters, the actual connection status will have to come from cellect_panoptes

**Comment by camallen** [comment]
sweet! nice one.
